blank_issues_enabled: false
contact_links:
  - name: Discussion / 讨论
    url: https://github.com/xus2019/TodoBoard/discussions
    about: For questions and general discussion, please use Discussions instead of Issues.
